# Generated by Django 5.0.3 on 2024-03-28 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_dailycalorierecord'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailycalorierecord',
            name='total_calories',
            field=models.IntegerField(default=2000),
        ),
    ]
